adjust scripts

diff --git a/scripts/bootstrap b/scripts/bootstrap
--- a/scripts/bootstrap
+++ b/scripts/bootstrap
@@ -18,8 +18,8 @@ fi;
 
 # If brew install failed then exit.
 if [[ -z $(command -v brew) ]]; then
-    echo homebrew install failed
-    exit;
+    echo "homebrew install failed"
+    exit 1
 fi;
 
 
@@ -32,5 +32,5 @@ fi;
 # @see https://sdkman.io/install
 [[ -z $(command -v sdk) ]] && curl -s "https://get.sdkman.io" | bash
 
-echo "bootstrap successful."
+echo "Bootstrap successful."
 exit 0
